### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [Origin5665/RegExpForm#3]
Хорошая работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- требования к веткам соблюдены

**Надо исправить**
- Удалить файл main.js. Так как он не используется.
- `http://2-domains.ru` - Не проходит валидацию корректный домен
- `http://google.ru///1///2///3` - количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- `http://11.11.11.11:0000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Можно лучше**
- С комитами все отлично, но можно немного лучше. Часто возникает соблазн написать комментарий к коммиту вида "fixes" или "first commit" или "add change". Лучше описывать коммиты подробнее.
Делать коммиты, когда:
1) выполнил единицу работы
2) сделал изменения, которые потом может потребоваться отменить
Интересная статья по [ссылке](https://habr.com/ru/company/Voximplant/blog/276695/)

**Comment by Origin5665** [comment]
**Здравствуйте!**

**Comment by Origin5665** [comment]
**Здравствуйте.** 

Переделал шаблон для ссылки. 
[Работа здесь](https://github.com/Origin5665/RegExpForm/blob/master/README.md)

**Comment by Origin5665** [comment]
Нужно ли загрузить ссылку в тренажер?

**Comment by talantbekov123** [comment]
Добрый день, ссылка на тренажер не нужна.
Хорошая работа, все комментарии исправленны! Похвально! Принимаю.
